import json
from datetime import datetime, timezone
from typing import List, Dict, Any

def get_current_time_iso():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

def extract_failed_actions(execution_log: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    return [log for log in execution_log if log.get("status") == "FAILED" and log.get("requires_recovery")]

def simulate_fallback_execution(action_id: str, failed_entry: Dict[str, Any], fallback: Dict[str, Any]) -> Dict[str, Any]:
    """
    Execute the fallback for a failed action.
    Uses the fallback spec from the action plan (generated by agent4/LLM).
    Builds a realistic generic simulation — no hardcoded domain content.
    """
    fb_type   = fallback.get("type", "ALERT")
    fb_target = fallback.get("target_system", "fallback_channel")
    fb_title  = fallback.get("title", f"Fallback for {action_id}")
    fb_desc   = fallback.get("description", "Fallback action executed via alternative route.")
    uid       = action_id.split("_")[-1] if "_" in action_id else "000"

    print(f"  [RecoveryAgent] Executing fallback for {action_id}: {fb_type} via {fb_target}…")

    # Determine realistic endpoint and response based on fallback type
    endpoint_map = {
        "ALERT":   f"POST /{fb_target.replace('_','-')}/notifications",
        "PUBLISH": f"POST /{fb_target.replace('_','-')}/documents",
        "UPDATE":  f"PATCH /{fb_target.replace('_','-')}/records",
        "ANALYZE": f"POST /{fb_target.replace('_','-')}/jobs",
        "MONITOR": f"POST /{fb_target.replace('_','-')}/schedules",
    }
    response_map = {
        "ALERT":   {"message_id": f"fb_msg_{uid}", "status": "delivered", "recipients": 6},
        "PUBLISH": {"document_id": f"fb_doc_{uid}", "status": "published", "route": fb_target},
        "UPDATE":  {"records_updated": 1, "status": "updated"},
        "ANALYZE": {"job_id": f"fb_job_{uid}", "status": "queued"},
        "MONITOR": {"job_id": f"fb_mon_{uid}", "status": "scheduled"},
    }

    endpoint = endpoint_map.get(fb_type, f"POST /{fb_target.replace('_','-')}/execute")
    response = response_map.get(fb_type, {"status": "success"})
    response["recovered_at"] = get_current_time_iso()

    # Determine which downstream blocked actions this unblocks
    side_effects = [
        f"Content delivered via fallback route ({fb_target}) instead of primary.",
        f"Fallback logged as {fb_type} at {get_current_time_iso()}.",
        "Dependent downstream actions eligible for unblocking."
    ]

    return {
        "action_id": action_id,
        "original_error": failed_entry.get("error", "unknown"),
        "fallback_used": fallback,
        "status": "RECOVERED",
        "duration_ms": 380,
        "recovery_output": {
            "api_endpoint": endpoint,
            "request_payload": {
                "title": fb_title,
                "description": fb_desc[:200],
                "fallback_for": action_id
            },
            "response": response
        },
        "side_effects_resolved": side_effects
    }

def run(execution_log: List[Dict[str, Any]], original_plan: List[Dict[str, Any]]) -> Dict[str, Any]:
    print("[RecoveryAgent] Initializing Recovery Stage...")
    
    # Identify failures
    failed_logs = extract_failed_actions(execution_log)
    print(f"[RecoveryAgent] Found {len(failed_logs)} failed action(s) requiring recovery.")
    
    recovery_logs = []
    recovered_action_ids = []
    
    for failed in failed_logs:
        action_id = failed.get("action_id")
        
        # Find original action to get fallback
        original_action = next((a for a in original_plan if a.get("action_id") == action_id), None)
        
        if not original_action or "fallback" not in original_action:
            print(f"  [RecoveryAgent] No fallback found for {action_id}. Recovery failed.")
            continue
            
        fallback = original_action["fallback"]
        
        # Execute fallback, passing the failed log entry for context
        recovery_result = simulate_fallback_execution(action_id, failed, fallback)
        recovery_logs.append(recovery_result)
        recovered_action_ids.append(action_id)
        
    # Check for blocked actions that can now be unblocked
    unblocked_actions = []
    for log in execution_log:
        if log.get("status") == "SKIPPED":
            # Simplified mock check for unblocking
            action_id = log.get("action_id")
            original_action = next((a for a in original_plan if a.get("action_id") == action_id), None)
            if original_action:
                deps = original_action.get("depends_on", [])
                if any(dep in recovered_action_ids for dep in deps):
                    unblocked_actions.append(action_id)
                    print(f"  [RecoveryAgent] Action {action_id} is now UNBLOCKED.")
                    
    print(f"[RecoveryAgent] Done — {len(recovered_action_ids)} actions recovered, {len(unblocked_actions)} actions unblocked.")
    
    return {
        "recovered_actions": recovery_logs,
        "unblocked_actions": unblocked_actions,
        "recovery_summary": f"Successfully executed fallback for {len(recovered_action_ids)} failed actions."
    }

if __name__ == "__main__":
    # Mock inputs
    mock_execution_log = [
        {
            "action_id": "act_002",
            "status": "FAILED",
            "requires_recovery": True
        },
        {
            "action_id": "act_004",
            "status": "SKIPPED",
            "error": "Blocked — act_002 (PUBLISH) failed."
        }
    ]
    
    mock_original_plan = [
        {
            "action_id": "act_002",
            "depends_on": ["act_001"],
            "fallback": {
                "title": "Email Draft",
                "type": "PUBLISH",
                "target_system": "email_draft",
                "description": "If portal API unavailable, send as formatted email attachment to distribution list"
            }
        },
        {
            "action_id": "act_004",
            "depends_on": ["act_002", "act_003"]
        }
    ]
    
    print(json.dumps(run(mock_execution_log, mock_original_plan), indent=2))
